### ISSUE TITLE
job_parameters missing in the job spec lead to key_error in dsflow-run

### ISSUE THREAD

**Issue by du-phan** [dsflow-io/dsflow-sample-project#1]
In the `job_specs.yaml` of dashboard-prevision job, there is no `job_parameters`, which will led to the error when we do `dsflow run ...` as `dsflow-run.py` expects that variable for the Try-Exception part. 

```python 
Traceback (most recent call last):
  File "/Users/duphan/Documents/dsflow-sample-project/../dsflow/dsflow/dsflow-run.py", line 45, in <module>
    raise(Exception("missing parameters:", job_specs_raw["job_parameters"]))
KeyError: 'job_parameters'
```

**Comment by pmleveque** [comment]
Actually the problem is in the README:  
I wrote `dsflow run dashboard-previsions_pluie_paris 2017-11-24` by this job doesn't take any parameters. I will fix the README, and add an exception to `dsflow run` if undue parameters are passed.
